language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
# command to install dependencies
install:
    - pip install -e .
script:
    - py.test tests --cov cr.cube
after_success:
    - coveralls 
