language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
# command to install dependencies
install:
    - pip install -e .
script:
    - py.test tests --cov cr.cube
after_success:
    - coveralls 
