name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        id: python-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[testing]
          python -m pip install flake8
          python -m pip install pytest-xdist
      - name: Lint with flake8
        id: flake8
        run: |
          flake8 . --count --statistics
      - name: Test with pytest
        id: tests
        run: |
          python -m pytest -n auto

  coveralls:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[testing]
          python -m pip install coveralls
      - name: Test with pytest
        run: python -m pytest --cov=cr.cube
      - name: Coveralls
        run: coveralls
